services:
  atuador:
    build: ./atuador
    #image: cleidsonramos/atuador:v1 
    container_name: atuador_pbl
    ports:
      - "8081:8081/tcp"
    restart: always

  integrador:
    build: ./integrador
    #image: cleidsonramos/integrador:v3
    container_name: integrador_pbl
    ports:
      - "8080:8080/udp"
      - "8082:8082/tcp"
    depends_on:
      - atuador
    environment:
      - ATUADOR_ADDR=atuador:8081 
    restart: always

  sensor:
    build: ./sensor
    #image: cleidsonramos/sensor:v3
    container_name: sensor_pbl
    depends_on:
      - integrador
    environment:
      - SERVER_ADDR=integrador:8080
    restart: always
    
  cliente:
    build: ./cliente
    #image: cleidsonramos/cliente:v1
    container_name: cliente_pbl
    depends_on:
      - integrador
    environment:
      - INTEGRADOR_ADDR=integrador:8082
    stdin_open: true # Mantém o stdin aberto para interação
    tty: true        # Mantém o terminal aberto para interação
