services:
  atuador:
    build: ./atuador
    container_name: atuador_pbl
    ports:
      - "8081:8081/tcp"
    restart: always

  integrador:
    build: ./integrador
    container_name: integrador_pbl
    ports:
      - "8080:8080/udp"
    restart: always

  sensor:
    build: ./sensor
    container_name: sensor_pbl
    depends_on:
      - integrador
    environment:
      - SERVER_ADDR=integrador:8080
    restart: always